version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    env_file:
      - ./client/.env
    depends_on:
      - server

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - '5173:80'
    env_file:
      - ./admin/.env
    depends_on:
      - server

  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
