name: 🐞 Bug Report
description: Report a problem with Cartify
title: '[Bug] <short description>'
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much info as possible.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser, Node.js version, MongoDB, etc.
      placeholder: 'e.g., Windows 11, Chrome, Node 20, MongoDB Atlas'
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug
      placeholder: 'Steps to reproduce, actual vs expected behavior...'
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs/screenshots
      description: Paste any error logs or screenshots here
      placeholder: 'Attach screenshots or terminal output'
    validations:
      required: false
