name: 💡 Feature Request
description: Suggest an idea or improvement
title: '[Feature] <describe your idea>'
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing an idea! We appreciate your feedback.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve?
      placeholder: 'I wish Cartify could...'
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Suggested Solution
      description: How would you like it to work?
      placeholder: 'Describe your proposed solution...'
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Which part of the project does this affect?
      options:
        - Frontend (React)
        - Backend (Express/MongoDB)
        - Auth (OAuth/JWT)
        - Database Design
        - UI/UX
        - Other
    validations:
      required: true
