name: Integration tests check & build

# 1. Trigger: workflow run
on:
  pull_request:
    branches: ['master']

# 2. Job: job run on virtual machine
jobs:
  integration-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    # services:
    #   mongo:
    #     image: mongo
    #     ports:
    #       - 27017:27017
    #     options: >-
    #       --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
    #       --health-interval=10s
    #       --health-timeout=5s
    #       --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 3. Steps: Install packages, run test, or deploy

      # - name: Install server dependencies
      #   run: npm install
      #   working-directory: server

      # - name: Run server test
      #   run: npm test
      #   working-directory: server

      - name: Install client dependencies
        run: npm install
        working-directory: client

      - name: Build react + vite app
        run: npm run build
        working-directory: client

      - name: Install admin dependencies
        run: npm install
        working-directory: admin

      - name: Build react + vite + ts App
        run: npm run build
        working-directory: admin

      # - name: Run Test
      #   run: npm test
